// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqvbxhirnhdxaezkddtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdmJ4aGlybmhkeGFlemtkZHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTE4MTIsImV4cCI6MjA3NDI4NzgxMn0.hN6fIueovrPDP4SV1-tN7s9qq94h-lTyv4B3wjjUhxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});